-- Triggers for History with ${dbms}
-- File generated by "${generator.templateName}"

-- *** DROP Triggers ***
/*
<#list config.tables as histTable>
<#if histTable.insertTrigger != ''>
DROP TRIGGER ${histTable.insertTrigger};
</#if>
<#if histTable.updateTrigger != ''>
DROP TRIGGER ${histTable.updateTrigger};
</#if>
</#list>
*/

-- *** CREATE Triggers ***

<#list config.tables as histTable>
<#assign table = catalog.getTable(histTable.tableName)>
-- ** Triggers for ${histTable.tableName}
<#if histTable.insertTrigger != ''>
CREATE OR REPLACE TRIGGER ${histTable.insertTrigger}
  AFTER INSERT ON ${histTable.tableName}
  REFERENCING NEW AS NEW
  FOR EACH ROW
BEGIN
  INSERT INTO H_JOURNAL (ID,  HIST_TIME, HIST_CONTEXTID, HIST_TABLE)
  VALUES (:NEW.${table.primaryKey.getColumn(0)}, SYSDATE, h_session.getContextId, '${histTable.tableName?lower_case}');
END;
/
</#if>
<#if histTable.updateTrigger != ''>

CREATE OR REPLACE TRIGGER ${histTable.updateTrigger}
  AFTER DELETE OR UPDATE
  ON ${histTable.tableName}
  REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
BEGIN
  IF(DELETING) THEN
    INSERT INTO ${histTable.historyTable} (
    <#list table.columns as column><#if !histTable.excludeColumns?seq_contains(column.columnName)>  ${column.columnName},
    </#if></#list>  HIST_TIME, HIST_CONTEXTID, HIST_TYPE)
    VALUES (
    <#list table.columns as column><#if !histTable.excludeColumns?seq_contains(column.columnName)>  :OLD.${column.columnName},
    </#if></#list>  SYSDATE, h_session.getContextId, 'D');
  ELSIF (UPDATING AND :OLD.VERSION != :NEW.VERSION) THEN
    INSERT INTO ${histTable.historyTable} (
    <#list table.columns as column><#if !histTable.excludeColumns?seq_contains(column.columnName)>  ${column.columnName},
    </#if></#list>  HIST_TIME, HIST_CONTEXTID, HIST_TYPE)
    VALUES (
    <#list table.columns as column><#if !histTable.excludeColumns?seq_contains(column.columnName)>  :OLD.${column.columnName},
    </#if></#list>  SYSDATE, h_session.getContextId, 'U');
  END IF;
END;
/
</#if>

</#list>

