-- Tables of Catalog<#if (catalog.schemaName)??> '${catalog.schemaName}'</#if> with ${dbms}
-- File generated by "${generator.templateName}"

/* ---------------------------------------------------------------------- */
/* Sequences                                                              */
/* ---------------------------------------------------------------------- */
<#list catalog.sequences?sort as sequence>
CREATE SEQUENCE ${sequence.sequenceName}
    <#if (sequence.start)??>START WITH  ${sequence.start}
    </#if><#if (sequence.increment)??>INCREMENT BY  ${sequence.increment}
    </#if><#if (sequence.minValue)??>MINVALUE  ${sequence.minValue}
    </#if><#if (sequence.maxValue)??>MAXVALUE  ${sequence.maxValue}
    </#if><#if sequence.isNoMinValue()>NOMINVALUE
    </#if><#if sequence.isNoMaxValue()>NOMAXVALUE
    </#if><#if !sequence.isCycle()>nocycle
    </#if><#if !sequence.isOrder()>noorder
    </#if><#if sequence.isNoCache()>NOCACHE<#else>CACHE  ${sequence.cache}</#if>;

</#list>

/* ---------------------------------------------------------------------- */
/* Tables                                                                 */
/* ---------------------------------------------------------------------- */
<#list catalog.tableCollection?sort as table>
<#include "create-table.ftl">

</#list>

/* ---------------------------------------------------------------------- */
/* Foreign key constraints                                                */
/* ---------------------------------------------------------------------- */
<#list catalog.tableCollection?sort as table>
<#list table.foreignKeys?sort as foreignKey>
<#include "alter-table-add-foreignkey.ftl">
</#list>
</#list>