<?xml version="1.0" encoding="UTF-8"?>
<!--
    Prototype for historyConfig.xml of Catalog<#if (catalog.schemaName)??> '${catalog.schemaName}'</#if> with ${dbms}
    File generated by "${generator.templateName}"
-->
<historyConfig>

<#list catalog.tableCollection?sort as table>
  <tableConfig>
    <tableName>${table.tableName?lower_case}</tableName>
  </tableConfig>
</#list>

</historyConfig>
