<?xml version="1.0" encoding="UTF-8"?>
<!--
    Prototype for data.xml of Catalog<#if (catalog.schemaName)??> '${catalog.schemaName}'</#if> with ${dbms}
    File generated by "${generator.templateName}"
-->
<dataset>

<#list catalog.tableCollection?sort as table>
<${table.tableName?lower_case} <#list table.columns as column>
  ${column.columnName}="a${column.typeName}"</#list>/>
  
</#list>

</dataset>
